train_path: data/ynat-v1.1/ynat-v1.1_train.json
dev_path: data/ynat-v1.1/ynat-v1.1_dev.json
save_path: ckpt
epochs: 20
batch_size: 4
lr: 0.00008
finetune_type: base
max_seq_len: 32
val_interval: 1
log_interval: 1
save_interval: 1
train_log_path: log/train.log
test_log_path: log/test.log
load_path: False
test_only: False
preprocess: False
